# Generated by Django 3.2.11 on 2022-02-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_script'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Script',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
