# Generated by Django 3.2.11 on 2022-01-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='profile_pic',
        ),
    ]
