# Generated by Django 3.2.11 on 2022-02-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_userdetail_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
