# Generated by Django 3.2.11 on 2022-02-03 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_tags_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='video',
            new_name='video_ref',
        ),
    ]
