# Generated by Django 3.2.11 on 2022-02-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_heroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimage',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
